# Generated by Django 4.2.6 on 2023-11-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addfaculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Faculty_Name', models.CharField(max_length=100)),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Position', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
