# Generated by Django 4.2.6 on 2023-11-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addfaculty', '0002_allreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='allreview',
            name='Rating',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='allreview',
            name='Subject',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='allreview',
            name='Suggetion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='allreview',
            name='Position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
